name: elwarsha
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  anim_search_bar: ^2.0.3
  animated_splash_screen: ^1.3.0
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  curved_labeled_navigation_bar: ^2.0.2
  email_auth: ^1.0.0
  email_otp: ^1.0.4
  email_validator: ^2.1.17
  firebase_auth: ^4.2.6
  firebase_core: ^2.5.0
  firebase_database: ^10.0.10
  firebase_storage: ^11.0.11
  flutter:
    sdk: flutter

  flutter_keyboard_visibility: ^5.4.0
  flutter_launcher_icons: ^0.11.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3
  hexcolor: ^3.0.1
  image_picker: ^0.8.6+1
  input_history_text_field: ^0.2.0
  intl_phone_number_input: ^0.7.2
  liquid_swipe: ^3.0.0
  loading_indicator: ^3.1.0
  modal_bottom_sheet: ^2.1.2
  page_transition: ^2.0.9
  qr_flutter: ^4.0.0
  search_page: ^2.3.0
  shared_preferences: ^2.0.18
  slide_countdown: ^0.5.0
  smooth_page_indicator: ^1.0.0+2
  timer_count_down: ^2.2.0
  google_sign_in: ^6.0.1
  font_awesome_flutter: ^10.4.0
  flutter_bloc: ^8.1.2
  top_snackbar_flutter: ^3.0.0+1
  flutter_facebook_auth: ^5.0.7
  cloud_firestore: ^4.4.3
  location: ^4.4.0
  flutter_osm_plugin: ^0.50.0
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  quickalert: ^1.0.1
  flutter_localizations:
    sdk: flutter
  intl: any
  pull_to_refresh: ^2.0.0


dev_dependencies:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.1.2
  http: ^0.13.5

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/icone.png
  adaptive_icon_background: "#345D68"
  adaptive_icon_foreground: assets/images/1024.png

  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/dev/
    - assets/images/Icons/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-VariableFont_wght.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
