// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUD_LoX1slw7KMcbn3AgGazMUxRMNXh3o',
    appId: '1:284481971558:web:3b42b399796c86368194a7',
    messagingSenderId: '284481971558',
    projectId: 'elwarsha-ff004',
    authDomain: 'elwarsha-ff004.firebaseapp.com',
    databaseURL: 'https://elwarsha-ff004-default-rtdb.firebaseio.com',
    storageBucket: 'elwarsha-ff004.appspot.com',
    measurementId: 'G-GTCN4TQ93S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUD_LoX1slw7KMcbn3AgGazMUxRMNXh3o',
    appId: '1:284481971558:android:baf6394126a2c4da8194a7',
    messagingSenderId: '284481971558',
    projectId: 'elwarsha-ff004',
    databaseURL: 'https://elwarsha-ff004-default-rtdb.firebaseio.com',
    storageBucket: 'elwarsha-ff004.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWRRmFz3GnbJmN7gLMJTbwOti3pKqjHjA',
    appId: '1:284481971558:ios:7e28b6ca44509cbf8194a7',
    messagingSenderId: '284481971558',
    projectId: 'elwarsha-ff004',
    databaseURL: 'https://elwarsha-ff004-default-rtdb.firebaseio.com',
    storageBucket: 'elwarsha-ff004.appspot.com',
    androidClientId: '284481971558-re6kkqn2e7uscn2p5ap4earq08kp4m6j.apps.googleusercontent.com',
    iosClientId: '284481971558-9ar7b0mtik9acu62gi3f3kogqj0m10do.apps.googleusercontent.com',
    iosBundleId: 'com.example.elwarsha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWRRmFz3GnbJmN7gLMJTbwOti3pKqjHjA',
    appId: '1:284481971558:ios:7e28b6ca44509cbf8194a7',
    messagingSenderId: '284481971558',
    projectId: 'elwarsha-ff004',
    databaseURL: 'https://elwarsha-ff004-default-rtdb.firebaseio.com',
    storageBucket: 'elwarsha-ff004.appspot.com',
    androidClientId: '284481971558-re6kkqn2e7uscn2p5ap4earq08kp4m6j.apps.googleusercontent.com',
    iosClientId: '284481971558-9ar7b0mtik9acu62gi3f3kogqj0m10do.apps.googleusercontent.com',
    iosBundleId: 'com.example.elwarsha',
  );
}
